---

name: Infralovers Changelog Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  changelog-automation:
    uses: infralovers/.github/.github/workflows/changelog-automation.yml@main
    secrets: inherit
